laravel-nodejs/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Route::resource('/index','HomeController');
Route::resource('/film','FilmController');
Route::view('/login','login')->name('login');
Route::post('/login/save','FilmController@signin')->name('signin');
Route::get('/daftar','HomeController@daftar')->name('daftar');

laravel-nodejs/app/Http/Controllers/FilmController.php
<?php

namespace App\Http\Controllers;

use File;
use Validator;
use GuzzleHttp\Client;
use Illuminate\Http\Request;

class FilmController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $client = new Client([
            'base_uri' => 'http://localhost:3000',
        ]);

        $response = $client->request('GET', 'film');
        $data['films'] = json_decode($response->getBody()->getContents());
        
         if ($response->getStatusCode() == 200) {
            return view('film.index',$data);
         }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('film.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $file = $request->file('image');
        $filename = str_random(50).".".$file->getClientOriginalExtension();
        $request['image'] = $filename;
        $validator = Validator::make($request->file(), [
			'image' => 'image|mimes:jpeg,jpg,png|max:2048'
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors());
        } else {
            $file->move('images',$filename);
        }
        
        $client = new Client([
            'base_uri' => 'http://localhost:3000',
        ]);
        
        $response = $client->request('POST','/film',[
            'form_params' => $request->input()  
        ]);

        if ($response->getStatusCode() == 200) {
            return redirect()->route('film.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $client = new Client([
            'base_uri' => 'http://localhost:3000',
        ]);

        $response = $client->request('GET', 'film/'.$id);
        $data['film'] = json_decode($response->getBody()->getContents());

        if ($response->getStatusCode() == 200) {
            return view('film.show', $data);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = new Client([
            'base_uri' => 'http://localhost:3000',
        ]);

        $response = $client->request('GET', 'film/'.$id);
        $data['film'] = json_decode($response->getBody()->getContents());
        
        if ($response->getStatusCode() == 200) {
           return view('film.edit', $data);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->except('old_image');

        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $filename = str_random(50).".".$file->getClientOriginalExtension();
            $data['image'] = $filename;
            $validator = Validator::make($request->file(), [
			    'image' => 'image|mimes:jpeg,jpg,png|max:2048'
            ]);

            if ($validator->fails()) {
                return redirect()->back()->withErrors($validator->errors());
            } else {
                File::delete('images'.$request->old_image);
                $file->move('images',$filename);
            }
        }

        $client = new Client([
            'base_uri' => 'http://localhost:3000',
        ]);

        $response = $client->request('PUT','film/'.$id,[
            'form_params' => $data
        ]);
        
        if ($response->getStatusCode() == 200) {
            return redirect()->route('film.show',$id);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = new Client([
            'base_uri' => 'http://localhost:3000',
        ]);

        $response = $client->request('DELETE', 'film/'.$id);
        if ($response->getStatusCode() == 200) {
           return redirect()->route('film.index');
        }
    }
    
    public function signin(Request $request)
    {
        if ($request->username == "admin" && $request->password == "movie21") {
            return redirect()->route('film.index');
        } else {
            return redirect(url('/login'));
        }
        
    }
}

laravel-nodejs/resources/views/film/create.blade.php
@extends('layouts.app')

@section('content')
<!-- page content -->
<div class="right_col" role="main">
  <div class="">

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Movie</h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">

          <form class="form-horizontal form-label-left" action="{{ route('film.store') }}" enctype="multipart/form-data"
            method="post" novalidate>
            @csrf
            <span class="section">Movie Info</span>

            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="judul">Judul <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input id="judul" class="form-control col-md-7 col-xs-12" data-validate-length-range="6"
                  data-validate-words="2" name="judul" placeholder="" required="required" type="text">
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="tayang">Tayang <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <div class='input-group date' id='myDatepicker4'>
                  <input id="tayang" type='text' class="form-control" readonly="readonly" name="tayang" />
                    <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="bioskop">Bioskop <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input id="bioskop" class="form-control col-md-7 col-xs-12" data-validate-length-range="6"
                  data-validate-words="2" name="bioskop" placeholder="" required="required" type="text">
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="harga">Harga <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input id="harga" class="form-control col-md-7 col-xs-12" data-validate-length-range="6"
                  data-validate-words="2" name="harga" placeholder="ex: Rp." required="required" type="text">
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="trailer">Video Trailer <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input id="trailer" class="form-control col-md-7 col-xs-12" data-validate-length-range="6"
                  data-validate-words="2" name="trailer" placeholder="https://www.youtube.com/embed/..." required="required" type="text">
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="sinopsis">Sinopsis <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <textarea id="sinopsis" required="required" name="sinopsis" class="form-control col-md-7 col-xs-12"></textarea>
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="image">Image <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input id="image" class="form-control col-md-7 col-xs-12" data-validate-length-range="6"
                  data-validate-words="2" name="image" required="required" type="file">
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-md-offset-3">
                <a type="submit" class="btn btn-primary">Cancel</a>
                <button id="send" type="submit" class="btn btn-success">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<!-- /page content -->
@endsection

laravel-nodejs/resources/views/film/edit.blade.php
@extends('layouts.app')

@section('content')
<!-- page content -->
<div class="right_col" role="main">
  <div class="">

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Movie</h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">

          <form class="form-horizontal form-label-left" action="{{ route('film.update',$film->_id) }}" enctype="multipart/form-data"
            method="post" novalidate>
            @csrf
            {{ method_field('PUT') }}
            <span class="section">Movie Info</span>
            <input type="hidden" value="{{ $film->image }}" name="old_image">
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="judul">Judul <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input id="judul" class="form-control col-md-7 col-xs-12" data-validate-length-range="6"
                  data-validate-words="2" name="judul" value="{{ $film->judul }}" required="required" type="text">
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="tayang">Tayang <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <div class='input-group date' id='myDatepicker4'>
                  <input id="tayang" type='text' class="form-control" readonly="readonly" name="tayang" value="{{ $film->tayang }}"/>
                    <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="bioskop">Bioskop <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input id="bioskop" class="form-control col-md-7 col-xs-12" data-validate-length-range="6"
                  data-validate-words="2" name="bioskop" value="{{ $film->bioskop }}" required="required" type="text">
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="harga">Harga <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input id="harga" class="form-control col-md-7 col-xs-12" data-validate-length-range="6"
                  data-validate-words="2" name="harga" placeholder="ex: Rp." value="{{ $film->harga }}" required="required"
                  type="text">
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="trailer">Video Trailer <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input id="trailer" class="form-control col-md-7 col-xs-12" data-validate-length-range="6"
                  data-validate-words="2" name="trailer" value="{{ $film->trailer }}" required="required" type="text">
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="sinopsis">Sinopsis <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <textarea id="sinopsis" required="required" name="sinopsis" class="form-control col-md-7 col-xs-12">{{ $film->sinopsis }}</textarea>
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="image">Image <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input id="image" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2"
                  name="image" required="required" type="file">
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-md-offset-3">
                <a href="{{ route('film.show',$film->_id) }}" class="btn btn-primary">Cancel</a>
                <button id="send" type="submit" class="btn btn-success">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<!-- /page content -->
@endsection

laravel-nodejs/resources/views/film/index.blade.php
@extends('layouts.app')

@section('content')
<!-- page content -->
<div class="right_col" role="main">
  <div class="">

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Movie</h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table id="datatable-buttons" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Judul</th>
                <th>Jam Tayang</th>
                <th>Bioskop</th>
                <th>Harga</th>
              </tr>
            </thead>
            <tbody>
              @foreach($films as $film)
              <tr>
                <td><a href="{{ route('film.show',$film->_id) }}">{{ $film->judul }}</a></td>
                <td>{{ $film->tayang }}</td>
                <td>{{ $film->bioskop }}</td>
                <td>Rp {{ strrev(implode('.',str_split(strrev(strval($film->harga)),3))) }}</td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<!-- /page content -->
@endsection

laravel-nodejs/resources/views/film/show.blade.php
@extends('layouts.app')

@section('content')
<!-- page content -->
<div class="right_col" role="main">

  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Movie Information</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="col-md-7 col-sm-7 col-xs-12">
              <div class="product-image">
                <img src="{{ asset('images/'.$film->image) }}"/>
              </div>
            </div>
            <div class="col-md-5 col-sm-5 col-xs-12" style="border:0px solid #e5e5e5;">

              <h3 class="prod_title">{{ $film->judul }}</h3>

              <p>{{ $film->sinopsis }}</p>
              <br />
              <br />

              <div class="">
                <label for="">Tayang: </label>
                <h2>{{ $film->tayang }}</h2><br />
                <label for="">Bioskop: </label>
                <h2>{{ $film->bioskop }}</small></h2>
              </div>
              <br />

              <div class="">
                <div class="product_price">
                  <h1 class="price">Rp {{ strrev(implode('.',str_split(strrev(strval($film->harga)),3))) }}</h1>
                  <br>
                </div>
              </div>

              <div id="action_bar">
                <a href="{{ route('film.edit', $film->_id) }}" class="btn btn-warning btn-lg">Edit</a>
                <!-- <a class="btn btn-danger btn-lg">Delete</a> -->
                <form action="{{ route('film.destroy', $film->_id) }}" method="POST" style="display:inline-block !important;">
                  <input type="hidden" name="_method" value="DELETE">
                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                  <input type="submit" class="btn btn-danger" value="Delete" />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->
@endsection