laravel-nodejs/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Route::resource('/index','HomeController');
Route::resource('/film','FilmController');
Route::view('/login','login')->name('login');
Route::post('/login/save','FilmController@signin')->name('signin');
Route::get('/daftar','HomeController@daftar')->name('daftar');

laravel-nodejs/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use GuzzleHttp\Client;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $client = new Client([
            'base_uri' => 'http://localhost:3000',
        ]);

        $response = $client->request('GET', 'film');
        $data['films'] = json_decode($response->getBody()->getContents());
        
         if ($response->getStatusCode() == 200) {
            return view('home.index',$data);
         }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $client = new Client([
            'base_uri' => 'http://localhost:3000',
        ]);

        $response = $client->request('GET', 'film/'.$id);
        $data['film'] = json_decode($response->getBody()->getContents());

        if ($response->getStatusCode() == 200) {
            return view('home.show', $data);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    
    public function daftar()
    {
        $client = new Client([
            'base_uri' => 'http://localhost:3000',
        ]);

        $response = $client->request('GET', 'film');
        $data['films'] = json_decode($response->getBody()->getContents());
        
         if ($response->getStatusCode() == 200) {
            return view('home.daftar',$data);
         }
    }
}

laravel-nodejs/resources/views/home/daftar.blade.php
@extends('layouts.home')

@section('content')
<div class="portfolio-wrap">
    <div class="container">
        <div class="row portfolio-container">
            @foreach($films as $film)
            <div class="col-12 col-md-6 col-lg-4 portfolio-item">
                <div class="portfolio-cont">
                    <a href="#"><img src="{{ asset('images/'.$film->image) }}" alt=""></a>

                    <h3 class="entry-title"><a href="{{ route('index.show',$film->_id) }}">{{ $film->judul }}</a></h3>
                    <h4>Rp {{ strrev(implode('.',str_split(strrev(strval($film->harga)),3))) }}</h4>
                </div>
            </div>
            @endforeach
        </div>

        <div class="row">
            <div class="col-12 d-flex justify-content-center mt-72">
                <a href="#" class="btn gradient-bg load-more-btn">Load More</a>
            </div>
        </div>
    </div>
</div>
@endsection

laravel-nodejs/resources/views/home/index.blade.php
@extends('layouts.home')

@section('content')
<div class="swiper-container hero-slider">
    <div class="swiper-wrapper">
        <div class="swiper-slide hero-content-wrap">
            <img src="{{ asset('front/images/slider1.jpg')}}" alt="">

            <div class="hero-content-overlay position-absolute w-100 h-100">
                <div class="container h-100">
                    <div class="row h-100">
                        <div class="col-12 col-lg-8 d-flex flex-column justify-content-center align-items-start">
                            <header class="entry-header">
                                <h1>CGV Blitz</h1>
                                <h4></h4>
                            </header><!-- .entry-header -->

                            <div class="entry-content mt-4">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tempus vestibulum
                                    mauris quis aliquam. Integer accumsan sodales odio, id tempus ullamcorper</p>
                            </div><!-- .entry-content -->

                            <!-- <footer class="entry-footer d-flex flex-wrap align-items-center mt-5">
                                    <a href="#" class="btn gradient-bg mr-2">Donate Now</a>
                                    <a href="#" class="btn orange-border">Read More</a>
                                </footer>.entry-footer -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                </div><!-- .container -->
            </div><!-- .hero-content-overlay -->
        </div><!-- .hero-content-wrap -->

        <div class="swiper-slide hero-content-wrap">
            <img src="{{ asset('front/images/slider2.jpg')}}" alt="">

            <div class="hero-content-overlay position-absolute w-100 h-100">
                <div class="container h-100">
                    <div class="row h-100">
                        <div class="col-12 col-lg-8 d-flex flex-column justify-content-center align-items-start">
                            <header class="entry-header">
                                <h1>Cinema XXI</h1>
                                <h4></h4>
                            </header><!-- .entry-header -->

                            <div class="entry-content mt-4">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tempus vestibulum
                                    mauris quis aliquam. Integer accumsan sodales odio, id tempus ullamcorper</p>
                            </div><!-- .entry-content -->

                            <!-- <footer class="entry-footer d-flex flex-wrap align-items-center mt-5">
                                    <a href="#" class="btn gradient-bg mr-2">Donate Now</a>
                                    <a href="#" class="btn orange-border">Read More</a>
                                </footer>.entry-footer -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                </div><!-- .container -->
            </div><!-- .hero-content-overlay -->
        </div><!-- .hero-content-wrap -->

        <div class="swiper-slide hero-content-wrap">
            <img src="{{ asset('front/images/slider3.jpg')}}" alt="">

            <div class="hero-content-overlay position-absolute w-100 h-100">
                <div class="container h-100">
                    <div class="row h-100">
                        <div class="col-12 col-lg-8 d-flex flex-column justify-content-center align-items-start">
                            <header class="entry-header">
                                <h1>Cinemaxx</h1>
                                <h4></h4>
                            </header><!-- .entry-header -->

                            <div class="entry-content mt-4">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tempus vestibulum
                                    mauris quis aliquam. Integer accumsan sodales odio, id tempus ullamcorper</p>
                            </div><!-- .entry-content -->

                            <!-- <footer class="entry-footer d-flex flex-wrap align-items-center mt-5">
                                    <a href="#" class="btn gradient-bg mr-2">Donate Now</a>
                                    <a href="#" class="btn orange-border">Read More</a>
                                </footer>.entry-footer -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                </div><!-- .container -->
            </div><!-- .hero-content-overlay -->
        </div><!-- .hero-content-wrap -->
    </div><!-- .swiper-wrapper -->

    <div class="pagination-wrap position-absolute w-100">
        <div class="container">
            <div class="swiper-pagination"></div>
        </div><!-- .container -->
    </div><!-- .pagination-wrap -->

    <!-- Add Arrows -->
    <div class="swiper-button-next flex justify-content-center align-items-center">
        <span><svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                <path d="M1171 960q0 13-10 23l-466 466q-10 10-23 10t-23-10l-50-50q-10-10-10-23t10-23l393-393-393-393q-10-10-10-23t10-23l50-50q10-10 23-10t23 10l466 466q10 10 10 23z" /></svg></span>
    </div>

    <div class="swiper-button-prev flex justify-content-center align-items-center">
        <span><svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                <path d="M1203 544q0 13-10 23l-393 393 393 393q10 10 10 23t-10 23l-50 50q-10 10-23 10t-23-10l-466-466q-10-10-10-23t10-23l466-466q10-10 23-10t23 10l50 50q10 10 10 23z" /></svg></span>
    </div>
</div><!-- .hero-slider -->

<div class="home-page-icon-boxes">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 mt-4 mt-lg-0">
                <div class="icon-box">
                    <figure class="d-flex justify-content-center">
                        <!-- <img src="{{ asset('front/images/hands-gray.png')}}" alt="">
                            <img src="{{ asset('front/images/hands-white.png')}}" alt=""> -->
                        <i class="fa fa-book" style="font-size:50px"></i>
                    </figure>

                    <header class="entry-header">
                        <h3 class="entry-title">Fitur</h3>
                    </header>

                    <div class="entry-content">
                        <p>Terdapat fitur harga, jam penayangan, dan bioskop tempat menonton.</p>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-4 mt-4 mt-lg-0">
                <div class="icon-box">
                    <figure class="d-flex justify-content-center">
                        <!-- <img src="{{ asset('front/images/donation-gray.png')}}" alt="">
                            <img src="{{ asset('front/images/donation-white.png')}}" alt=""> -->
                        <i class="fa fa-film" style="font-size:50px"></i>
                    </figure>

                    <header class="entry-header">
                        <h3 class="entry-title">Film</h3>
                    </header>

                    <div class="entry-content">
                        <p>Menyajikan berbagai macam film di seluruh bioskop di Indonesia.</p>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-4 mt-4 mt-lg-0">
                <div class="icon-box">
                    <figure class="d-flex justify-content-center">
                        <!-- <img src="{{ asset('front/images/charity-gray.png')}}" alt="">
                            <img src="{{ asset('front/images/charity-white.png')}}" alt=""> -->
                        <i class="fa fa-tv" style="font-size:50px"></i>
                    </figure>

                    <header class="entry-header">
                        <h3 class="entry-title">Bioskop</h3>
                    </header>

                    <div class="entry-content">
                        <p>Menyajikan daftar bioskop di seluruh Indonesia. </p>
                    </div>
                </div>
            </div>
        </div><!-- .row -->
    </div><!-- .container -->
</div><!-- .home-page-icon-boxes -->

<div class="home-page-welcome">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-6 order-2 order-lg-1">
                <div class="welcome-content">
                    <header class="entry-header">
                        <h2 class="entry-title">Sejarah Film Pertama</h2>
                    </header><!-- .entry-header -->

                    <div class="entry-content mt-5">
                        <p>Film komersial pertama di dunia diputar di Grand Cafe, Paris, pada 28 Desember 1895. Film tersebut dibuat oleh Louis
                        dan Auguste Lumiere, yakni kakak beradik asal Prancis pembuat kamera sekaligus proyektor yang disebut Cinematographe.
                        
                        Kakak beradik yang dikenal dengan Lumiere Brothers itu meluncurkan penemuannya ke publik pada Maret 1895, dengan
                        menampilkan film singkat berisi cuplikan pekerja yang meninggalkan pabrik Lumiere.
                        
                        Pada 28 Desember, kedua bersaudara itu menampilkan serangkaian adegan singkat kehidupan Prancis dan mengenakan biaya
                        masuk untuk pertama kalinya, yang kemudian disebut sebagai bioskop pertama di dunia.</p>
                    </div><!-- .entry-content -->
                </div><!-- .welcome-content -->
            </div><!-- .col -->

            <div class="col-12 col-lg-6 mt-4 order-1 order-lg-2">
                <img src="{{ asset('front/images/film.jpg')}}" alt="welcome">
            </div><!-- .col -->
        </div><!-- .row -->
    </div><!-- .container -->
</div><!-- .home-page-icon-boxes -->

<div class="our-causes">
    <div class="container">
        <div class="row">
            <div class="coL-12">
                <div class="section-heading">
                    <h2 class="entry-title">Film</h2>
                </div><!-- .section-heading -->
            </div><!-- .col -->
        </div><!-- .row -->

        <div class="row">
            <div class="col-12">
                <div class="swiper-container causes-slider">
                    <div class="swiper-wrapper">
                        @foreach($films as $film)
                        <div class="swiper-slide">
                            <div class="cause-wrap">
                                <figure class="m-0">
                                    <img src="{{ asset('images/'.$film->image) }}" height="350" alt="">
                                </figure>

                                <div class="cause-content-wrap">
                                    <header class="entry-header d-flex flex-wrap align-items-center">
                                        <h3 class="entry-title w-100 m-0"><a href="{{ route('index.show',$film->_id) }}">{{ $film->judul }}</a></h3>
                                    </header><!-- .entry-header -->

                                    <div class="entry-content">
                                        <p class="m-0">{{ str_limit($film->sinopsis,130) }}</p>
                                    </div><!-- .entry-content -->

                                    <div class="fund-raised w-100">
                                        <div class="fund-raised-details d-flex flex-wrap justify-content-between align-items-center">
                                            <div class="fund-raised-goal mt-4">
                                                Rp {{ strrev(implode('.',str_split(strrev(strval($film->harga)),3))) }}
                                            </div><!-- .fund-raised-goal -->
                                        </div><!-- .fund-raised-details -->
                                    </div><!-- .fund-raised -->
                                </div><!-- .cause-content-wrap -->
                            </div><!-- .cause-wrap -->
                        </div><!-- .swiper-slide -->
                        @endforeach
                    </div><!-- .swiper-wrapper -->

                </div><!-- .swiper-container -->

                <!-- Add Arrows -->
                <div class="swiper-button-next flex justify-content-center align-items-center">
                    <span><svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                            <path d="M1171 960q0 13-10 23l-466 466q-10 10-23 10t-23-10l-50-50q-10-10-10-23t10-23l393-393-393-393q-10-10-10-23t10-23l50-50q10-10 23-10t23 10l466 466q10 10 10 23z" /></svg></span>
                </div>

                <div class="swiper-button-prev flex justify-content-center align-items-center">
                    <span><svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                            <path d="M1203 544q0 13-10 23l-393 393 393 393q10 10 10 23t-10 23l-50 50q-10 10-23 10t-23-10l-466-466q-10-10-10-23t10-23l466-466q10-10 23-10t23 10l50 50q10 10 10 23z" /></svg></span>
                </div>
            </div><!-- .col -->
        </div><!-- .row -->
    </div><!-- .container -->
</div><!-- .our-causes -->
@endsection

laravel-nodejs/resources/views/home/show.blade.php
@extends('layouts.home')

@section('content')
<div class="home-page-welcome">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-6 order-2 order-lg-1">
                <div class="welcome-content">
                        <header class="entry-header">
                            <h2 class="entry-title">{{ $film->judul }}</h2>
                        </header><!-- .entry-header -->

                        <div class="entry-content mt-5">
                            <p>{{ $film->sinopsis }}</p><br />
                            <p>Tanggal Tayang:<br><span style="font-size:20px;">{{ $film->tayang }}</span></p><br />
                            <p>Tempat Bioskop:<br><span style="font-size:30px;">{{ $film->bioskop }}</span></p><br />
                            <b style="font-size:50px;">Rp {{ strrev(implode('.',str_split(strrev(strval($film->harga)),3))) }}</b>
                        </div><!-- .entry-content -->

                        <div class="entry-footer mt-5">
                            <a href="{{ route('index.index') }}" class="btn gradient-bg mr-2">Back</a>
                            <a href="javascript:void(0);" class="btn mymodal-btn">Trailer</a>
                            <div class="mymodal-overlay">
                                <div class="mymodal">
                                    <a href="javascript:void" class="mybtn-close"><i class="fa fa-times"></i></a>
                                    <iframe src="{{ $film->trailer }}" class="col-12" style="height: 100%;padding: 0 !important;" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                </div>
                            </div>
                        </div><!-- .entry-footer -->
                    </div><!-- .welcome-content -->
            </div><!-- .col -->

            <div class="col-12 col-lg-6 mt-4 order-1 order-lg-2">
                <img src="{{ asset('images/'.$film->image)}}" alt="welcome">
            </div><!-- .col -->
        </div><!-- .row -->
    </div><!-- .container -->
</div><!-- .home-page-icon-boxes -->
@endsection